### PR TITLE
Added ignoreWithStartPath

### PR DESCRIPTION
**Pull request by whitef0x0**

### CODE REVIEW

**Comment by patmood** [comment]
Hey thanks for the contribution! What's the use case for this?

Can you give me some more info and some documentation to the README?

**Comment by whitef0x0** [comment]
@patmood this allows you to ignore a subdomain if you are using a subdomain for your main site that you don't want processed by this middleware.

**Comment by whitef0x0** [comment]
maybe ignoreWithSubDomain would be clearer?

**Comment by patmood** [comment]
This could actually replace the `ignoreWWW` option.

An option called `ignore` that took a string or array would be simplest.

If you'd like to do that and update the tests/docs I'd be happy to merge it.

If you don't have the time/motivation, I can update and publish it.

**Comment by whitef0x0** [comment]
I'd be happy to do that

**Comment by whitef0x0** [comment]
@patmood done

**Comment by whitef0x0** [comment]
@patmood all I need to do is update the tests and I'll be done

**Comment by whitef0x0** [comment]
Actually sorry, I mixed up the definition of 'ignore'.

ignore tells the module to ignore the url if it has a subdomain matching it. (i.e. if you are using app.mydomain.com for your main url and don't want wildcard-subdomaisn to add a /namespace/app uri to all of your requesrs).

stripSubdomain does was ignoreWWW does, it essentially strips a matching subdomain from the request string

**Comment by roundrobin** [comment]
When is being merged into master?

**Comment by patmood** [comment]
@roundrobin `ignore` and `stripSubdomain` are essentially the same thing. You are correct that you should be able to specify subdomain to ignore, rather than assuming 'www' is the only one.

I think the best way forward is:
1. remove `stripSubdomain` option completely
2. move `ignore` check to go before this line: `if (!subdomains.length) return next()` and use the splice method. Once you remove the "ignored" subdomain, it will not modify the request unless there are more subdomains.
3. make all tests pass

**Comment by roundrobin** [comment]
@patmood Sorry to ask again, but how would I go about if I want to exclude the subdomain "support" for instance. You mentioned the `ignore` option, but I can't seem to find anything in the documentation about it.

**Comment by patmood** [comment]
@roundrobin I've just updated the main package on npm to v1.1.0. You can add a whitelist in the options. Just take a look at the new README and open a new issue if there's any problems 👍 

Closing this PR as the main package has this functionality now.

**Comment by roundrobin** [comment]
@patmood Thanks so much!!!!

**Pull request closed without merging**
