### PR TITLE
Sometimes req.subdomains returns array[0]

### PR DESCRIPTION
**Pull request by caco0516**
Add new object to req object  to avoid zero index array problem . Now you can access subdomains array using **req.subdomain.subs**

### CODE REVIEW

**Comment by timelf123** [comment]
LGTM, @patmood what about you?

**Comment by patmood** [comment]
Thanks for the PR!

Can you explain the use case for this? I don't see how `req.subdomain.subs` is any different to using `req.subdomains`?

**Comment by caco0516** [comment]
@patmood Hi , first thanks for this useful tool , so this is what happened to me , I was trying to use your library on my project , Its a multi-tenant app so I wanted to use sub-domain as identifier for every client , when I tried to use this middleware with routers , with 2 or 3 subrouting levels , value for req.subdomains always was null or empty , I was searching online and found a blog that explain some best practices for writing node js middleware , one of the items explained when you modify req or res , you should add a new property with 2 levels , for example req.subdomain.subs , I just tried this and voilá it worked.

**Comment by patmood** [comment]
Interesting... Do you have a link to the post?

I think if `subdomains` was initialized with an empty array, it would fix the problem and you can reliably use `req.subdomains` in your route.

Would you like to try that?

I'm glad to see it being used, I'd be happy to refactor it, write some tests, and update on NPM.

**Comment by patmood** [comment]
I've published a new v1.0.0 release npm so I'm going to close this.

Let me know if you find any issues

**Pull request closed without merging**
